# Generated by Django 4.2.7 on 2023-11-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='size',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='sizes',
            field=models.ManyToManyField(blank=True, editable=False, null=True, to='main.size'),
        ),
    ]
