# Generated by Django 4.2.7 on 2023-11-10 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_remove_link_sizes_delete_size_link_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='sizes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ImagineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
