# Generated by Django 4.2.7 on 2023-11-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_link_sizes_imagineorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagineorder',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagineorder',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
