# Generated by Django 4.2.7 on 2023-11-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_imagineorder_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='have',
            field=models.BooleanField(default=True),
        ),
    ]
