# Generated by Django 4.2.7 on 2023-11-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_imagineorder_date_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagineorder',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
