# Generated by Django 4.2.7 on 2023-11-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_imagineorder_date_alter_package_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagineorder',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='imagineorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='have',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='sizes',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
