# Generated by Django 4.2.7 on 2023-11-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_imagineorder_text_alter_imagineorder_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
