# Generated by Django 4.2.7 on 2023-11-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_pretrans'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretrans',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
