# Generated by Django 4.2.7 on 2023-11-13 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_imagineorder_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagineVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=1000)),
                ('percent', models.IntegerField(default=0)),
                ('done', models.BooleanField(default=False)),
                ('result', models.JSONField(blank=True, null=True)),
                ('image', models.URLField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
