# Generated by Django 4.2.7 on 2023-11-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_imaginevariation_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagineVariation',
        ),
    ]
