# Generated by Django 4.2.7 on 2023-11-13 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_imagineorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagineorder',
            name='bid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imagineorder',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagineorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='main.imagineorder'),
        ),
    ]
