# Generated by Django 4.2.7 on 2023-11-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_imagineorder_bid_alter_imagineorder_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagineorder',
            name='buttons',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
