# Generated by Django 4.2.7 on 2023-11-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_imagineorder_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagineorder',
            name='act',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
