# Generated by Django 4.2.7 on 2023-11-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_imagineorder_act'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagineorder',
            name='act',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
