# Generated by Django 4.2.7 on 2023-11-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_transactions_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceSwaped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
            ],
        ),
        migrations.AlterField(
            model_name='link',
            name='sizes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
