# Generated by Django 4.2.7 on 2023-11-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_faceswaped_alter_link_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceswaped',
            name='image',
            field=models.URLField(),
        ),
    ]
