# Generated by Django 4.2.7 on 2023-11-18 18:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_faceswaped_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceswaped',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
