# Generated by Django 4.2.7 on 2023-11-18 18:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_faceswaped_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceswaped',
            name='id',
        ),
        migrations.AddField(
            model_name='faceswaped',
            name='fsid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
