# Generated by Django 4.2.7 on 2023-11-18 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0031_remove_faceswaped_id_faceswaped_fsid'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceswaped',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
