# Generated by Django 4.2.7 on 2023-11-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_faceswaped_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceswaped',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
