# Generated by Django 4.2.7 on 2023-11-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_coupon_bonus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonus',
            old_name='percent',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='amount',
            new_name='percent',
        ),
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(default='6h263Wzd', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='qnIGekik', max_length=8, null=True),
        ),
    ]
