# Generated by Django 4.2.7 on 2023-11-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_bonus_code_alter_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(default='EvhLYi46', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='oJpDl4ZX', max_length=8, null=True),
        ),
    ]
