# Generated by Django 4.2.7 on 2023-11-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_bonus_code_alter_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagineorder',
            name='progress',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(blank=True, default='ZoesX7Cj', max_length=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='tw9NKvUL', max_length=8, null=True),
        ),
    ]
