# Generated by Django 4.2.7 on 2023-11-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_imagineorder_progress_alter_bonus_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(blank=True, default='41T9H0cR', max_length=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='2ZVLEFSC', max_length=8, null=True),
        ),
    ]
