# Generated by Django 4.2.7 on 2023-11-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_gptchatroom_alter_bonus_code_alter_coupon_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(blank=True, default='R82xrFaa', max_length=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='ScemekY5', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='amount',
            field=models.FloatField(),
        ),
    ]
