# Generated by Django 4.2.7 on 2023-11-29 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_bonus_code_alter_coupon_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(blank=True, default='4in0Q8nU', max_length=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='rtwFPnmU', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='gptmessages',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='main.gptchatroom'),
        ),
    ]
