# Generated by Django 4.2.7 on 2023-11-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_bonus_code_alter_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptchatroom',
            name='first_message',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(blank=True, default='hB0FqDKU', max_length=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='JSstxwRa', max_length=8, null=True),
        ),
    ]
