# Generated by Django 4.2.7 on 2023-12-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_adddetails_imagedetails_mimic_parameters_sizes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sizes',
            new_name='AddDetail',
        ),
        migrations.RenameModel(
            old_name='ImageDetails',
            new_name='ImageDetail',
        ),
        migrations.RenameModel(
            old_name='AddDetails',
            new_name='Parameter',
        ),
        migrations.RenameModel(
            old_name='Parameters',
            new_name='Size',
        ),
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(blank=True, default='L1V6DpcD', max_length=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='0SE1rGxS', max_length=8, null=True),
        ),
    ]
