# Generated by Django 4.2.7 on 2023-12-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_alter_bonus_code_alter_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='default',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='maximum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='minimum',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(blank=True, default='g2EmbkE0', max_length=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='uLTWip6O', max_length=8, null=True),
        ),
    ]
