# Generated by Django 4.2.7 on 2023-12-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_parameter_default_parameter_maximum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='image',
        ),
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(blank=True, default='ENi8BaN7', max_length=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='OqMht1Ig', max_length=8, null=True),
        ),
    ]
