# Generated by Django 4.2.7 on 2023-12-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_remove_parameter_image_alter_bonus_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(blank=True, default='KW7KZbze', max_length=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='55dGL8u9', max_length=8, null=True),
        ),
    ]
