# Generated by Django 4.2.7 on 2023-12-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_remove_post_text_post_content_alter_bonus_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
        migrations.RemoveField(
            model_name='post',
            name='h1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='h2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='h3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(blank=True, default='nMYZgUbs', max_length=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='1HATTYVQ', max_length=8, null=True),
        ),
    ]
