# Generated by Django 4.2.7 on 2023-12-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_remove_post_file_remove_post_h1_remove_post_h2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to='file'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(blank=True, default='pJ8cXbIS', max_length=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='ZrdSDXYg', max_length=8, null=True),
        ),
    ]
