# Generated by Django 4.2.7 on 2023-12-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_post_file_alter_bonus_code_alter_coupon_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file',
            new_name='files',
        ),
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(blank=True, default='TbyTctXl', max_length=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='U8cLVXfP', max_length=8, null=True),
        ),
    ]
