# Generated by Django 4.2.7 on 2023-12-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_traning_alter_bonus_code_alter_coupon_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Traning',
            new_name='Training',
        ),
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(blank=True, default='kJrfg3My', max_length=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='NaejD16P', max_length=8, null=True),
        ),
    ]
