# Generated by Django 4.2.7 on 2023-12-17 11:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_rename_traning_training_alter_bonus_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(blank=True, default='VMT01nwR', max_length=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='TuCNhmNv', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
