# Generated by Django 4.2.7 on 2023-12-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_alter_bonus_code_alter_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(blank=True, default='M9j6IACh', max_length=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='JXhGsRHL', max_length=8, null=True),
        ),
    ]
