# Generated by Django 4.2.7 on 2024-01-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_alter_bonus_code_alter_coupon_code_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddetail',
            name='image',
            field=models.ImageField(upload_to='param'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(blank=True, default='VcIviK0B', max_length=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='YW2nFkcI', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='imagedetail',
            name='image',
            field=models.ImageField(upload_to='param'),
        ),
        migrations.AlterField(
            model_name='mimic',
            name='image',
            field=models.ImageField(upload_to='param'),
        ),
        migrations.AlterField(
            model_name='size',
            name='image',
            field=models.ImageField(upload_to='param'),
        ),
    ]
