# Generated by Django 4.2.7 on 2024-01-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_alter_adddetail_image_alter_bonus_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceswaped',
            name='code',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(blank=True, default='Km9kd6rQ', max_length=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='YVmN9XD4', max_length=8, null=True),
        ),
    ]
