# Generated by Django 4.2.7 on 2024-01-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_faceswaped_code_alter_bonus_code_alter_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(blank=True, default='PpJBkFGW', max_length=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='EVOcFw5P', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='faceswaped',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
