# Generated by Django 4.2.7 on 2024-02-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_alter_bonus_code_alter_coupon_code_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(blank=True, default='iSxOlEj3', max_length=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='DMwRHMi9', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='code',
            field=models.IntegerField(null=True),
        ),
    ]
