# Generated by Django 4.2.7 on 2024-03-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_alter_bonus_code_alter_coupon_code_alter_phone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(blank=True, default='mxPmlfla', max_length=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='OfnAunx7', max_length=8, null=True),
        ),
    ]
