# Generated by Django 4.2.7 on 2024-08-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_alter_bonus_code_alter_coupon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='have',
        ),
        migrations.RemoveField(
            model_name='link',
            name='site',
        ),
        migrations.RemoveField(
            model_name='link',
            name='size',
        ),
        migrations.RemoveField(
            model_name='link',
            name='sizes',
        ),
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.FileField(null=True, upload_to='train'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(blank=True, default='WLZrH6VQ', max_length=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='Uvop5bWP', max_length=8, null=True),
        ),
    ]
