# Generated by Django 4.2.7 on 2024-08-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_alter_bonus_code_alter_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(blank=True, default='JhmlQ9Ll', max_length=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='qzHVrKOg', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.TextField(),
        ),
    ]
