# Generated by Django 4.2.7 on 2023-12-29 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiService', '0003_gptchatroom_user_gptmessages_gptchatroom_user_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptmessages',
            name='like',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
    ]
