# Generated by Django 4.2.7 on 2023-12-29 22:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiService', '0004_gptmessages_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptmessages',
            name='like',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='OrganizationAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='ApiService.organization')),
            ],
        ),
    ]
