# Generated by Django 4.2.7 on 2024-03-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiService', '0005_alter_gptmessages_like_organizationapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptmessages',
            name='context',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
