# Generated by Django 4.2.7 on 2024-03-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiService', '0006_gptmessages_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptmessages',
            name='context',
            field=models.TextField(null=True),
        ),
    ]
